name: Action Test
on: 
        push:
                branches:
                     - master
jobs:
        check-bats-version:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: borales/actions-yarn@v2.3.0
                          with:
                                cmd: install
                        - uses: borales/actions-yarn@v2.3.0
                          with: 
                                cmd: run tagchange templates/innerhtml_tt.html policy.js mypolicy
                        - uses: stefanzweifel/git-auto-commit-action@v4.12.0
                          with:
                                  commit_message: Checked trusted_types policy
                        

